#!/bin/bash
# design-context-hook.sh — SessionStart hook for Pencil design sessions
#
# Detects when Claude Code is running inside a design/ subfolder,
# reads the parent project's docs and code structure, and generates
# a design/CLAUDE.md that gives the AI full project context.
#
# This enables intelligent, context-aware design in Pencil without
# manual doc reading each session.

DESIGN_DIR="$(pwd)"
DESIGN_CLAUDE_MD="$DESIGN_DIR/CLAUDE.md"

# Only activate if we're inside a design/ directory
if [[ "$DESIGN_DIR" != */design ]]; then
  exit 0
fi

# Find the parent project root
PROJECT_ROOT="$(dirname "$DESIGN_DIR")"
PROJECT_NAME=$(basename "$PROJECT_ROOT")

# Verify it's actually a project (has CLAUDE.md or .git)
if [ ! -f "$PROJECT_ROOT/CLAUDE.md" ] && [ ! -d "$PROJECT_ROOT/.git" ]; then
  exit 0
fi

# Key directories
DOCS_DIR="$PROJECT_ROOT/docs"
FRONTEND_DIR="$PROJECT_ROOT/frontend/src"
BACKEND_DIR="$PROJECT_ROOT/backend"
CLAUDE_MD="$PROJECT_ROOT/CLAUDE.md"

# ─────────────────────────────────────────────
# Build design/CLAUDE.md
# ─────────────────────────────────────────────

cat > "$DESIGN_CLAUDE_MD" << 'HEADER'
# Design Context — Auto-Generated

> Auto-generated by design-context-hook.sh at session start.
> Bridges the parent project's codebase knowledge into the Pencil design environment.
> Regenerated every session — do NOT edit manually.

---

HEADER

echo "## Project: $PROJECT_NAME" >> "$DESIGN_CLAUDE_MD"
echo "" >> "$DESIGN_CLAUDE_MD"

# ── Extract project overview from CLAUDE.md ──
if [ -f "$CLAUDE_MD" ]; then
  echo "## Project Overview" >> "$DESIGN_CLAUDE_MD"
  echo "" >> "$DESIGN_CLAUDE_MD"
  # Get the overview paragraph (between ## Project Overview and next ##)
  awk '/^## Project Overview/{found=1; next} /^## /{if(found) exit} found' "$CLAUDE_MD" | head -15 >> "$DESIGN_CLAUDE_MD"
  echo "" >> "$DESIGN_CLAUDE_MD"

  # ── Extract user flow ──
  FLOW=$(awk '/^## User Flow/{found=1; next} /^## /{if(found) exit} found' "$CLAUDE_MD" 2>/dev/null)
  if [ -n "$FLOW" ]; then
    echo "## User Flow" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "$FLOW" | head -25 >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
  fi

  # ── Extract frontend routes ──
  ROUTES=$(awk '/^## Frontend Routes/{found=1; next} /^## /{if(found) exit} found' "$CLAUDE_MD" 2>/dev/null)
  if [ -n "$ROUTES" ]; then
    echo "## Frontend Routes" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "$ROUTES" | head -40 >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
  fi

  # ── Extract two user roles ──
  ROLES=$(awk '/^## Two User Roles/{found=1; next} /^## /{if(found) exit} found' "$CLAUDE_MD" 2>/dev/null)
  if [ -n "$ROLES" ]; then
    echo "## User Roles" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "$ROLES" | head -15 >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
  fi

  # ── Extract frontend conventions ──
  CONVENTIONS=$(awk '/^### Frontend/{found=1; next} /^### /{if(found) exit} found' "$CLAUDE_MD" 2>/dev/null)
  if [ -n "$CONVENTIONS" ]; then
    echo "## Frontend Conventions" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "$CONVENTIONS" | head -15 >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
  fi
fi

# ── List available project documentation ──
if [ -d "$DOCS_DIR" ]; then
  DOC_FILES=$(find "$DOCS_DIR" -name "*.md" -print 2>/dev/null | sort)
  if [ -n "$DOC_FILES" ]; then
    echo "## Available Project Documentation" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "Read these using \`../docs/...\` paths when designing related screens:" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "$DOC_FILES" | while read -r doc; do
      REL_PATH="${doc#$PROJECT_ROOT/}"
      TITLE=$(head -n 1 "$doc" 2>/dev/null | sed 's/^#* *//')
      echo "- \`../$REL_PATH\` — $TITLE" >> "$DESIGN_CLAUDE_MD"
    done
    echo "" >> "$DESIGN_CLAUDE_MD"
  fi
fi

# ── List frontend pages for screen-to-code mapping ──
if [ -d "$FRONTEND_DIR/Pages" ]; then
  PAGE_FILES=$(find "$FRONTEND_DIR/Pages" \( -name "*.jsx" -o -name "*.tsx" \) -print 2>/dev/null | sort)
  if [ -n "$PAGE_FILES" ]; then
    echo "## Frontend Pages (screen-to-code mapping)" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "Each design screen corresponds to a frontend page. Read these for data flow and state:" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "$PAGE_FILES" | while read -r page; do
      REL_PATH="${page#$PROJECT_ROOT/}"
      echo "- \`../$REL_PATH\`" >> "$DESIGN_CLAUDE_MD"
    done
    echo "" >> "$DESIGN_CLAUDE_MD"
  fi
fi

# ── List frontend components ──
if [ -d "$FRONTEND_DIR/Components" ]; then
  COMP_FILES=$(find "$FRONTEND_DIR/Components" \( -name "*.jsx" -o -name "*.tsx" \) -print 2>/dev/null | sort)
  if [ -n "$COMP_FILES" ]; then
    echo "## Frontend Components" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "Existing UI components in the codebase:" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "$COMP_FILES" | while read -r comp; do
      REL_PATH="${comp#$PROJECT_ROOT/}"
      echo "- \`../$REL_PATH\`" >> "$DESIGN_CLAUDE_MD"
    done
    echo "" >> "$DESIGN_CLAUDE_MD"
  fi
fi

# ── List backend API routes if they exist ──
if [ -d "$BACKEND_DIR/api" ]; then
  API_FILES=$(find "$BACKEND_DIR/api" \( -name "*.py" -o -name "*.js" -o -name "*.ts" \) -print 2>/dev/null | sort)
  if [ -n "$API_FILES" ]; then
    echo "## Backend API Routes" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "API route files (read for understanding data shapes in designs):" >> "$DESIGN_CLAUDE_MD"
    echo "" >> "$DESIGN_CLAUDE_MD"
    echo "$API_FILES" | while read -r api; do
      REL_PATH="${api#$PROJECT_ROOT/}"
      echo "- \`../$REL_PATH\`" >> "$DESIGN_CLAUDE_MD"
    done
    echo "" >> "$DESIGN_CLAUDE_MD"
  fi
fi

# ── Auto-Research Rules ──
cat >> "$DESIGN_CLAUDE_MD" << 'RULES'
---

## Auto-Research Rules

**IMPORTANT: Follow these rules automatically when designing any screen.**

### Before Designing Any Screen:
1. Check the doc index and frontend pages listed above
2. If a matching planning doc exists, **READ IT** before designing (use `../docs/...` paths)
3. If a matching frontend page component exists, **READ IT** to understand data flow, Redux state, API calls, and conditional rendering
4. Use the actual data fields, state shapes, and user flows from the code — never guess

### Read-Only Access to Parent Project
- ALLOWED: Read any file in the parent project using `../` paths for research
- FORBIDDEN: Write, edit, or create any file outside `design/` — READ ONLY
- FORBIDDEN: Run git operations or any command that modifies the parent project
- If a design task suggests code changes are needed, TELL the user — do not make them

### Screen-to-Research Mapping
When the user mentions designing a screen related to a topic, automatically read the relevant docs and code:
- **Auth / Login / Signup screens** → read auth-related pages and docs
- **Dashboard screens** → read dashboard page component and mediator API routes
- **Onboarding screens** → read onboarding page components and planning docs
- **Breakout / Chat screens** → read breakout page and AI engine docs if available
- **Comparison screens** → read comparison page components and agreement-related docs
- **Profile screens** → read profile page component
- **Any new feature** → read the relevant planning doc first if one exists

RULES

# ── Design conventions ──
cat >> "$DESIGN_CLAUDE_MD" << 'CONVENTIONS'

## Design Conventions

- Design screens in the `.pen` file using Pencil MCP tools
- Match the existing design system: check reusable components before creating new ones
- Branding follows the parent project's conventions (extract from CLAUDE.md or frontend code)
- When designing forms, read the corresponding API to know exact field names and validation rules
- When designing data displays (tables, cards, lists), read the corresponding page to know exact data shape

CONVENTIONS

# ─────────────────────────────────────────────
# Output summary for Claude to see at session start
# ─────────────────────────────────────────────

echo ""
echo "Design Context Hook"
echo "==================="
echo "Project: $PROJECT_NAME"
echo "Parent: $PROJECT_ROOT"
echo ""
echo "Injected into design/CLAUDE.md:"
[ -f "$CLAUDE_MD" ] && echo "  - Project overview, user flow, routes, roles from CLAUDE.md"
if [ -d "$DOCS_DIR" ]; then
  DOC_COUNT=$(find "$DOCS_DIR" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
  echo "  - $DOC_COUNT planning doc(s) indexed"
fi
if [ -d "$FRONTEND_DIR/Pages" ]; then
  PAGE_COUNT=$(find "$FRONTEND_DIR/Pages" \( -name "*.jsx" -o -name "*.tsx" \) 2>/dev/null | wc -l | tr -d ' ')
  echo "  - $PAGE_COUNT frontend page(s) listed"
fi
if [ -d "$FRONTEND_DIR/Components" ]; then
  COMP_COUNT=$(find "$FRONTEND_DIR/Components" \( -name "*.jsx" -o -name "*.tsx" \) 2>/dev/null | wc -l | tr -d ' ')
  echo "  - $COMP_COUNT frontend component(s) listed"
fi
if [ -d "$BACKEND_DIR/api" ]; then
  API_COUNT=$(find "$BACKEND_DIR/api" \( -name "*.py" -o -name "*.js" -o -name "*.ts" \) 2>/dev/null | wc -l | tr -d ' ')
  echo "  - $API_COUNT backend API route file(s) listed"
fi
echo ""
echo "  Auto-research rules active: Claude will read relevant"
echo "  docs and code automatically before designing screens."
echo ""
